### ISSUE TITLE
Documentation repo: Migrate documentation to Ampersand repo

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/Ampersand#1315]
**Depends on**
- [x] #1325 
- [x] #1316 
- [x] #1318 

**Problem Description**
Docusaurus currently shows the hello world page from the ampersand repo. However it needs to show the actual documentation.

**Tasks**
- [ ] Notify the Ampersand team with the expected end date.
- [x] Replace the contents of the "docs" folder in the Ampersand repo with the documentation from the documentation repo.
- [ ] Update the workflows to use the `main` branches instead of `development`

**Comment by basplijnaer** [comment]
The [docs](https://github.com/AmpersandTarski/Ampersand/tree/development/docs) folder on the `development` branch of the [Ampersand](https://github.com/AmpersandTarski/Ampersand) repo currently holds the contents of the [documantation](https://github.com/AmpersandTarski/documentation) repo to make sure that all markdown files compile correctly. The applied changes can be found [here](https://github.com/AmpersandTarski/Ampersand/issues/1326#issuecomment-1233886873).
The [docs](https://github.com/AmpersandTarski/Ampersand/tree/development/docs) folder should be updated with the latest version of the [GitBook documentation](https://github.com/AmpersandTarski/documentation) ones the [Docusaurus website](https://ampersandtarski.github.io/DocuGen/) is taken into production.
