### ISSUE TITLE
Github Actions: Deploy docusaurus on pull request from Prototype

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/ampersand#1325]
### Depends on
- [x] #1316 
- [x] #1318 

### Problem Definition
The same as #1316 for the [prototype repo](https://github.com/AmpersandTarski/prototype). Within the workflow, now not only copy the docs directory of the Ampersand repo, but also the docs directory of Prototype. In the one-pager, these directories should co-exist. Maybe scaffold pages are required to make this happen. If so, these could be created and stored inside the new repo.

### Tasks
- [x] create a development branch.
- [x] Rename the doc directory to docs.
- [x] Make the workflow also trigger on a commit of the development branch of the Prototype repo. 
- [x] Document what you do
