### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by basplijnaer** [AmpersandTarski/Ampersand#1336]
### Problem
Building the Docusaurus webpage currently gives the following warning:
```
Warning:  Docusaurus found broken links!

Please check the pages of your site in the list below, and make sure you don't reference any path that does not exist.
Note: it's possible to ignore broken links with the 'onBrokenLinks' Docusaurus configuration, and let the build pass.

Exhaustive list of all broken links found:

- On source page path = /DocuGen/docs/Ampersand/the-language-ampersand/patterns:
   -> linking to broken-reference (resolved as: /DocuGen/docs/Ampersand/the-language-ampersand/broken-reference)
```
This concerns the following file: [patterns.md](https://github.com/AmpersandTarski/Ampersand/blob/development/docs/the-language-ampersand/patterns.md)
### Tasks

Either:
- [ ] Remove the broken links
or
- [ ] Redirect the the broken links to an existing page

After the links have been fixed:
- [ ] Change the ci/cd so that broken links will let the build fail as well.
