### ISSUE TITLE
Runtime bug in the ArchiChecker

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#1464]
# What happened
```bash
sjo % ampersand data-analysis repositoryumcu.archimate
/Users/sjo00577/repositoryumcu.archimate has been interpreted as an Archi-repository.
!             Ampersand-v5.0.0 [feature/labels-in-ADL-files:c3d6ddff3*]
Not a valid NamePart: "Office 365"
CallStack (from HasCallStack):
  fatal, called at src/Ampersand/Input/Archi/ArchiAnalyze.hs:221:34 in ampersand-5.0.0-B1XilKuKFTSK4jjvTTkJYi:Ampersand.Input.Archi.ArchiAnalyze
ExitFailure 2
sjo % 
```
# What I expected
I expected Ampersand to generate a file called `Metamodel.adl`.

# Version of ampersand that was used

# Steps to reproduce

1. download and unzip [repositoryumcu.archimate.zip](https://github.com/AmpersandTarski/Ampersand/files/14138039/repositoryumcu.archimate.zip)
2. compile `repositoryumcu.archimate` with Ampersand-v5.0.0 [feature/labels-in-ADL-files:c3d6ddff3*] with:
```bash
ampersand data-analysis repositoryumcu.archimate
```
# Analysis
The ArchiChecker runs into illegal identifiers in the new namespace setup.

# TODO
 - [x] The module `Name.hs` has a `checkProperId` function. The desired behavior is to squish the illegal names and put the original name in a LABEL, so that the ArchiChecker will not produce errors that it did not produce before, and so that the ArchiMate modeler is not forced to impose Ampersand naming conventions to his models.
 - [ ] the same for concept names in the Excel importer, to save the modeler work when it is most needed.
 - [x] add `ampersand data-analysis repositoryumcu.archimate` to the regression test, to prevent some future bitrot

**Comment by hanjoosten** [comment]
Fixed
