### ISSUE TITLE
Remake RAP2 into RAP3

### ISSUE THREAD

**Issue by stefjoosten** [AmpersandTarski/Ampersand#449]
To modernize the course of the Open University of the Netherlands ["Ontwerpen met Bedrijfsregels"](http://portal.ou.nl/web/ontwerpen-met-bedrijfsregels) (OBR, Eng: rule based design), we need a remake of RAP2 in the modern technology. This remake is called RAP3. This issue is an epic rather than one backlog-item.

# Requirements

As a student in the OBR-course of the Open University of the Netherlands:
- [x] I must be able to submit an Ampersand-script in order to have it processed by RAP3.
- [x] I must get an analysis of concepts, relations, and rules, which is at least as good as RAP2, in order to analyse my script.
- [x] I must see the pictures from the functional design in my analysis.
- [x] I must get a diagnosis of my script, in order to get feedback on my work.
- [x] I must get a functional design from my script, in order to fulfil a course requirement.
- [x] I want to be able to include a .xlsx-file in my script, in order to work with the new didactical framework of Ampersand.
- [x] I want to edit my script interactively, so I can try things out without recompiling scripts all the time (issue #533).
- [x] I want to be able to run my script as an application on the web, so I can experience for myself how Ampersand generates information systems.
- [x] I want to reset my application by means of "reinstall database" without affecting the work of other students, so I can safely experiment with Ampersand.
- [ ] I want to retrieve Ampersand-scripts that I have previously submitted, at least during the period that I am registered for the OBR-course and I have not finished it, even when RAP3 might break down during that period, in order to finish the course without running the risk of losing my work.
- [ ] I want to register my permission to use my work for research, so I can decide for myself whether to make my work available for research at the Open University.
- [ ] I want access to decent documentation, in order to use RAP3 without getting stuck for help.
- [ ] I want a self-explaining user experience, with logical screen layouts, a minimal number of clicks, and no unnecessary obstacles for novice users (issue #481 contains a list of items). This item may not be checked off until all items in issue #481 are checked off.

As a tutor in the OBR-course of the Open University of the Netherlands:
- [x] I must look into the work of each student in order to follow his or her progress.
- [ ] I want to have an overview of the work of each student in order to follow his or her progress.
- [x] I want every script submitted by a student to be traceable to its submittor, in order to monitor and assess the work of students.

As account manager in the OBR-course of the Open University of the Netherlands:
- [x] I want an overview of all accounts of all students.
- [x] I want manage every account of each student.
- [x] I insist that RAP3 ensures that every activity is performed under a registered account.
- [x] I want my students to create and manage their own accounts.

As a researcher at the Open University of the Netherlands:
- [x] I want to save scripts submitted by students in order to analyse how students are learning to understand and use Ampersand.
- [x] I want every script submitted by a student, which has been compiled correctly, to be consolidated to foster any future research on these scripts.

As a maintenance engineer at the Open University of the Netherlands:
- [x] I want to deploy RAP3 on `rap.cs.ou.nl` in a reliable and reproducible manner, so deployment can be done by the Ampersand-team without the help of staff of the OU data center. For an instruction [click here](https://ampersandtarski.gitbooks.io/the-tools-we-use-for-ampersand/content/installation_of_rap.html)
- [x] I want RAP3 to run on a contemporary platform, which is already present on `rap.cs.ou.nl`, so that nobody has to keep maintaining obsolete technology.
- [ ] I want to load administrative information of all scripts that are present on the file system to be incorporated in the RAP3-database upon its installation, so that I can refresh the database without students losing their history  (issue #534).
- [x] I want to have all scripts of each student in one directory, which is traceable to the student, in order to move or remove the work of individual students.
- [x] I want the Ampersand-team to perform the database maintenance.
- [ ] I want the contexts of students to exist in the RAP3-database only as long as the student is logged in, to ensure that the database is not polluted excessively. This implies that students have to recompile their work if the reuse it in a following session.
- [x] I would like to deploy the RAP3 application by means of container technology in docker.

**Comment by hanjoosten** [comment]
This is too big for a single user story. To eat this elephant, we need to split it in doable pieces.

**Comment by stefjoosten** [comment]
Agreed, but I wanted to start it top-down.

**Comment by hanjoosten** [comment]
I have made a [description on how to install RAP3. ](https://ampersandtarski.gitbooks.io/the-tools-we-use-for-ampersand/content/installation_of_rap.html) @LloydRutledge , could you try to get RAP3 installed, based on these instructions?

**Comment by LloydRutledge** [comment]
Will do. Might take two weeks - next week I'm travelling to a conference. Thanks for setting it up!

**Comment by WolframKahl** [comment]
@hanjoosten , would a version that does not assume MSWindows and XAMPP be possible?

**Comment by hanjoosten** [comment]
@WolframKahl Yes, in fact RAP3 is just an instance of a prototype generated with Ampersand. So any machine where ampersand can be built, should do. If you want to give it a try, go ahead! Let me know if the description suffices. But please take note that with RAP3 we focus on the situation at Open Univ. And also that the current prototype is still very under construction. It isn't even beta-testable yet.

**Comment by stefjoosten** [comment]
Hi @WolframKahl, here is the situation. RAP3 will be installed on a Linux server at the OUNL: is.cs.ou.nl. The application will be accessible to all students who register themselves with an OU registration number. At the moment we are working with the tutors, instructing them how to deploy and maintain RAP3. It isn't difficult, but you have to do it a couple of times. That is happening now, as we are busy finishing the software for a production release. We have a go/no go at the end of october. If we miss that deadline, the OBR course will work with RAP2 for another 6 months.

**Comment by WolframKahl** [comment]
On Thu, Sep 22, 2016 at 11:35:15PM -0700, Stef Joosten wrote:
> we are busy finishing the software for a production release

Then I wish you good progress towards that, and good luck!

**Comment by sjcjoosten** [comment]
There are "must" "want" and "insist" items on the list. Is the software going to be ready for production release if all "must" and "insist" items have been resolved, or is there some other message intended for these three words?

**Comment by stefjoosten** [comment]
RAP3 will be ready for production when:
1. all must items on the list are checked, and
2. all insist items on the list are checked, and
3. Lloyd and Rogier are able to install RAP3 on `is.cs.ou.nl`, and
4. @LloydRutledge and @rvandewetering are satisfied that RAP3 is ready for production by performing their own acceptance tests on the prerelease of RAP3 on `is.cs.ou.nl`, and
5. @stefjoosten is satisfied that RAP3 is ready for production.

**Comment by stefjoosten** [comment]
I am currently busy installing RAP3 on a Linux LAMP configuration. Interesting for @WolframKahl and @LloydRutledge I presume. I have spent two full days now and I've come a long way. You can find some working stuff on http://52.174.4.78/RAP3/ . I have documented everything I did in `https://ampersandtarski.gitbooks.io/the-tools-we-use-for-ampersand/content/deploying-rap3-with-azure.html`, which is interesting if you want to deploy yourself.

I could use some help here. I am short on expertise of Linux and also Haskell-stack in combination with Git. Then we need to polish the RAP3 application itself, which requires front-end expertise, on which I'm short too. Please volunteer to assist! call me on 06 51 348895 or stef.joosten@ou.nl

**Comment by stefjoosten** [comment]
@WolframKahl , If you want you can try and reproduce the deployment of RAP3 on a server of your own. Follow `https://ampersandtarski.gitbooks.io/the-tools-we-use-for-ampersand/content/deploying-ounl-rap3.html` for instructions.
