### ISSUE TITLE
Implement meta model for navigation menu

### ISSUE THREAD

**Issue by RieksJ** [AmpersandTarski/Ampersand#578]
Sessions come in two flavours: those without an authenticated user (anonymous sessions) and those with an authenticated user. I would like to be able to specify for every interface:

- if it may be used in (i.e.: it appears in the menu bar of) anonymous sessions or not.
- if it may be used in non-anonymous sessions or not.

Roles is a partial solution. I can introduce the role 'Anonymous' in SIAM, and (de)activate it in (non-)anonymous sessions. However, this still does not allow me to specify an interface in a module (e.g. 'logout', to be defined in SIAM) that is to be available (in the menu bar) in every non-anonymous session.

@Michiel-s, I'd like to hear your suggestions here. (Also, I have trouble getting this role-based solution to work - I do not get the anonymous interfaces in the menu bar as I would expect - see SIAMv3 in the TNO development repo)

**Comment by Michiel-s** [comment]
After giving this some thought AND the keeping in mind that a possible solution must be consistent with the Ampersand approach, I have the following idea.

Let's introduce relations that determine the interfaces you can navigate to ( @RieksJ like I described 6 years ago in my master thesis). This is meta-modelling stuff we already do with the meatgrinder. You can then influence the navigation bar with the exec-engine as you like. This can also be the way forward to introduce menu structures with submenu's, bundling multiple interfaces under one button.
 
Hereby a start for such a model which we can implement in the frontend

```adl
CONTEXT NavigationBar IN ENGLISH
  
--[Top level navigation bar]-----------------------------------------------------------------------
  
  RELATION navBarItem[SESSION*MenuItem]
    MEANING "The menu items that are part of the top level navigation bar"
  
--[Generic menu item]------------------------------------------------------------------------------
  CONCEPT MenuItem ""
  
  RELATION label[MenuItem*Label] [UNI,TOT] 
    MEANING "The human readable text that represents the menu item and is shown to the user"
    CONCEPT Label ""
    REPRESENT Label TYPE ALPHANUMERIC
    
  RELATION ifc[MenuItem*Interface] [UNI] 
    MEANING "A menu item can direct to an interface"
    CONCEPT Interface "Representation of an Ampersand interface"
  
  RELATION url[MenuItem*URL] [UNI]
    MEANING "A menu item can direct to an (external) url. This can also be used for extensions like the excelimporter"
    CONCEPT URL "a uniform resource locator as defined by RFC3986"
    REPRESENT URL TYPE BIGALPHANUMERIC
  
  RELATION prio[MenuItem*Weight] [UNI,TOT] 
    MEANING "A menu item has a weight (default 0). The higher the weight the lower the menu item is placed in the menu"
    CONCEPT Weight ""
    REPRESENT Weight TYPE INTEGER
    
  RELATION subItemOf[MenuItem*MenuItem] [UNI,IRF,ASY]
    MEANING "A menu item can be a sub item of another menu item"
    
ENDCONTEXT
```

**Comment by RieksJ** [comment]
Seems like this goes in the right direction.
However, you're only addressing the menu-bar menu items.
Do you think that's the only menu we need to have, or will there be others?
If so, we could change the stuff to include a concept `Menu`, of which the menu-bar might be one.

**Comment by RieksJ** [comment]
First, I note that this is not just about the NavBar, but it may also apply to other menus, e.g. as in the figure below:
![image](https://cloud.githubusercontent.com/assets/8522589/21224786/1af4eb2c-c2ce-11e6-9549-86e0f5a318a6.png)

Since NavBar items can be menu's, too (because of `RELATION subItemOf[MenuItem*MenuItem]`), this would require the constraint `I /\ subItemOf~;subItemOf |- -(url;V \/ ifc;V)` for the purpose of preventing that users can navigate to an external or internal interface by clicking on a navbar-item that is actually a menu.

Perhaps it is better to clearly distinguish between menu's and items (quite similar to the `Sequences` patterns). This means that:

- `MenuItem`s can simply focus on being an item (with relations `label`, `ifc`, `url`, `prio`);
- `Menu` is defined as a collection of other `Menu`s and `MenuItem`s (with relations `isPartOf[Menu*Menu] and `isPartOf[MenuItem*Menu]`;
- `subItemOf` can be removed (it is actually replaced with `isPartOf[MenuItem*Menu]`);

If so, we still have some questions, such as:

- do we want `navBarItem[SESSION*MenuItem]` or  should it be `navBarMenu[SESSION*Menu]`?
- do we need a relation `navBarItem` for Menu(Items) of the navbar (and correspondingly a relation for every other menu(list)), or do we want a relation `sessionMenu[SESSION*Menu]`, with predefined atoms for specific menu's (e.g. `NavBar[Menu]`)
- we might also define `CLASSIFY NavBarMenu ISA MENU` and `RELATION sessionMenu[SESSION*NavBarMenu]`, which can be extended by replacing `NavBarMenu` by any other kind of menu that you might like.
- the current NavBarMenu(items) is(are) generated. Does that still have a purpose (e.g. as a default for the NavBarMenu(items)), or can we do without?

**Comment by Michiel-s** [comment]
Feature request moved from other issue
- [ ] The role-selector menu item should not contain devil-roles (e.g. `Anonymous`).

**Comment by Michiel-s** [comment]
Work in progress. I expect implementation soon and will share a meta model for the navigation menu.

**Comment by hanjoosten** [comment]
Is there still remaining work to be done for this issue, or should it be closed now?

**Comment by Michiel-s** [comment]
More work is needed. Only the top level navbar is implemented.

**Comment by RieksJ** [comment]
Here is a list of items that I think need to be addressed - there may be more issues:

- [ ] The role-selector menu item should NEVER contain system roles (previously called devil roles), which it currently does e.g. in anonymous sessions
- [ ] Meta interfaces, e.g. `Edit Navigation Menu` and `List All Interfaces` should only appear to developers that know they exist and make them viewable (e.g. by doing a default population)
- [ ] When sessionMenu items are affected, e.g. because the population of `sessionActiveRoles` has changed, the navbar should be refreshed

**Comment by RieksJ** [comment]
@Michiel-s Where can we find the current meta-model?

**Comment by Michiel-s** [comment]
Great. I agree with the list

In SystemContext.adl, builtin Ampersand Compiler

**Comment by hanjoosten** [comment]
This issue is becoming topical again. In the 4.0 branch, when a prototype is being generated, there are populations injected by means of the meatgrinder. Is the current PrototypeContext.adl file stable? There is something peculiar going on with the roles. I do not know exactly what goes on. The `anonymous` ROLE is also still causing a violation.

**Comment by Michiel-s** [comment]
Let me do a wild guess what's going on here:
You run the Ampersand compiler with `ampersand proto --verbose --sqlLogin ="root" --sqlPwd="" --build-recipe AtlasComplete CheckDanglingPurposes.adl`

So the build-recipe AtlasComplete is used. And because of the command `proto` the enablePrototype BuildRecipe is also added. I think the order here is wrong.

@hanjoosten can you verify that the order is:
1. Take Userscript
2. Perform AtlasComplete recipe
3. Perform enablePrototype recipe (grind + merge PrototypeContext)
It must be this order, because the PrototypeContext specifies rules that must hold. E.g. a Role must have a RoleName (i.e. RULE "TOT name[Role*RoleName]")

If you first grind the PrototypeContext and after that add other contexts (in this case grinded + merged FormalAmpersand) that have population that violates the rules from the PrototypeContext.

**Comment by hanjoosten** [comment]
this is exactly what I thought at first too. I have checked this, and I am pretty sure the order is correct. 
However, there are some things that need further investigation:
 * The way a dirtyId is generated differs. In the prototypeContext, the TYPE prefix has been removed about 9 months ago (commit 9273e5c0c072dadddef1cdffef619942a43d1c71 ) @Michiel-s , why is that required? 
 * There are two relations related with this, that might cause trouble too: `name[Role*RoleName]` (in FormalAmpersand) and  `label[Role*PF_Label]` (in PrototypeContext). 

I suspect that the combination of above points cause the trouble: Since the order is correct (see your spec above), the prototypeContext is grinded last. It will generate Role atoms with new dirtyId's. These are the ones that have no name in FormalAmpersand.

**Comment by hanjoosten** [comment]
I am going to test this assumption by (temporarily?) generate dirtyId's with the TYPE prefix. I wouldn't be surprised if that causes the violations to be gone. However, this might cause other damage, since there might be a reason that the TYPE prefix had been removed last year.

**Comment by Michiel-s** [comment]
@hanjoosten please don’t add the type prefix. It will break the prototype. Prefixing the atom with it’s type was once introduced from a FormalAmpersand perspective but we solved that differently.

**Comment by Michiel-s** [comment]
I think the only true solution here is to unify the atom ids. 
As you can understand I opt to remove the type prefix. What are the consequences from FormalAmpersand perspective?

**Comment by hanjoosten** [comment]
I am not sure yet if it is required. However, in FormalAmpersand, there is a `Concept` named `Atom`. **All** atoms in that concept need to have a unique value. That is the reason of the prefix. I did some research in the code and in git, but I couldn't find a proper explaination for the removal of the type. 
As you can see [in the Travis-ci log](https://travis-ci.org/AmpersandTarski/Ampersand/jobs/634420302#L5054), with this minor change all violations now have the prefix `Role_`. Except for `Anonymous`.

**Comment by Michiel-s** [comment]
The reason for removing the type prefix is as I pointed out above “This is because the grinded meta population corresponds to the generated json model files. They need to have the same identifier. Furthermore, it is also not needed and redundant to prefix the type, because that information is already provided by the concept/relation they are in.”
So maybe Travis doesn’t provide errors, a prototype won’t run
